# Generated by Django 4.0.5 on 2022-06-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_item_item_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='display_direction',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
