# Generated by Django 4.0.5 on 2022-07-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_item_next_page_item_page_nr_itemoption_next_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='spss_variable',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
