# Generated by Django 4.0.5 on 2022-07-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_item_spss_variable'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='spss_missing_value',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='spss_variable_label',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
