# Generated by Django 4.0.5 on 2022-07-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_item_spss_missing_value_item_spss_variable_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='spss_format',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemoption',
            name='spss_value_label',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemstatement',
            name='spss_format',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemstatement',
            name='spss_missing_value',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemstatement',
            name='spss_variable',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemstatement',
            name='spss_variable_label',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
