# Generated by Django 4.0.5 on 2022-07-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_item_spss_format_itemoption_spss_value_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemoption',
            name='score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
