# Generated by Django 4.0.5 on 2022-06-22 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soort',
            options={'managed': False, 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='spssdata',
            options={'managed': False, 'ordering': ['respondent_id', 'lijst_id', 'volgnr']},
        ),
        migrations.AlterModelOptions(
            name='vraag',
            options={'managed': False, 'ordering': ['lijst_id', 'volgnr']},
        ),
    ]
